name: Build iOS

on:
  push:
    branches:
      - main
      - ios-build-ci

jobs:
  build:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules
        run: yarn example
      - name: Optimize build cache
        uses: mikehardy/buildcache-action@v1
        continue-on-error: true
      - name: Install Pods
        run: yarn pods
      - name: Build App
        run: yarn example ios
