name: Build iOS

on:
  push:
    branches:
      - main
      - ios-build-ci

jobs:
  build:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules
        run: yarn install --frozen-lockfile --cwd ./example/
      - name: Restore build cache
        uses: mikehardy/buildcache-action@v1
        continue-on-error: true
      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true
          working-directory: example/ios
      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            example/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        run: yarn --cwd ./example/ios pods
      - name: Build App
        run: yarn example ios
