name: Build Android

on: workflow_call

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r24
      - name: Retrieve Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules
        run: yarn install && yarn install --cwd ./example/
      - name: Build lib
        run: cd android && ./gradlew assembleDebug --build-cache && cd ..
      - name: Build example app
        run: cd example/android && ./gradlew assembleDebug --build-cache && cd ../..
