name: Lint and compile

on: workflow_call

jobs:
  lint_and_compile:
    name: Lint and compile
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules
        run: yarn install && yarn install --cwd ./example/
      - name: Lint
        run: yarn lint
      - name: Compile TypeScript
        run: yarn typescript
