name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  call-code-check:
    uses: ./.github/workflows/code-check.yml

  call-build-ios:
    needs: call-code-check
    uses: ./.github/workflows/build-ios.yml

  call-build-android:
    needs: call-code-check
    uses: ./.github/workflows/build-android.yml
