name: Main workflow

on:
  push:
    branches:
      - main
      - ios-build-ci

jobs:
  call-code-check:
    uses: ./.github/workflows/code-check.yml

  call-build-ios:
    needs: call-code-check
    uses: ./.github/workflows/build-ios.yml
